// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_server.proto

package com.wjybxx.generatedmessage;

public final class PCSMessage {
  private PCSMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface server_client_first_messageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wjybxx.server_client_first_message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 uid = 1;</code>
     */
    int getUid();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * <pre>
   * 消息的命名格式由团队习惯决定
   * 服务器发给客户端的第一个消息
   * </pre>
   *
   * Protobuf type {@code wjybxx.server_client_first_message}
   */
  public  static final class server_client_first_message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wjybxx.server_client_first_message)
      server_client_first_messageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use server_client_first_message.newBuilder() to construct.
    private server_client_first_message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private server_client_first_message() {
      uid_ = 0;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private server_client_first_message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              uid_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_server_client_first_message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_server_client_first_message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wjybxx.generatedmessage.PCSMessage.server_client_first_message.class, com.wjybxx.generatedmessage.PCSMessage.server_client_first_message.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private int uid_;
    /**
     * <code>int32 uid = 1;</code>
     */
    public int getUid() {
      return uid_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0) {
        output.writeInt32(1, uid_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uid_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wjybxx.generatedmessage.PCSMessage.server_client_first_message)) {
        return super.equals(obj);
      }
      com.wjybxx.generatedmessage.PCSMessage.server_client_first_message other = (com.wjybxx.generatedmessage.PCSMessage.server_client_first_message) obj;

      boolean result = true;
      result = result && (getUid()
          == other.getUid());
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wjybxx.generatedmessage.PCSMessage.server_client_first_message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_first_message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_first_message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_first_message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_first_message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_first_message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_first_message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_first_message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_first_message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_first_message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_first_message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_first_message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wjybxx.generatedmessage.PCSMessage.server_client_first_message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 消息的命名格式由团队习惯决定
     * 服务器发给客户端的第一个消息
     * </pre>
     *
     * Protobuf type {@code wjybxx.server_client_first_message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wjybxx.server_client_first_message)
        com.wjybxx.generatedmessage.PCSMessage.server_client_first_messageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_server_client_first_message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_server_client_first_message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wjybxx.generatedmessage.PCSMessage.server_client_first_message.class, com.wjybxx.generatedmessage.PCSMessage.server_client_first_message.Builder.class);
      }

      // Construct using com.wjybxx.generatedmessage.PCSMessage.server_client_first_message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = 0;

        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_server_client_first_message_descriptor;
      }

      public com.wjybxx.generatedmessage.PCSMessage.server_client_first_message getDefaultInstanceForType() {
        return com.wjybxx.generatedmessage.PCSMessage.server_client_first_message.getDefaultInstance();
      }

      public com.wjybxx.generatedmessage.PCSMessage.server_client_first_message build() {
        com.wjybxx.generatedmessage.PCSMessage.server_client_first_message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wjybxx.generatedmessage.PCSMessage.server_client_first_message buildPartial() {
        com.wjybxx.generatedmessage.PCSMessage.server_client_first_message result = new com.wjybxx.generatedmessage.PCSMessage.server_client_first_message(this);
        result.uid_ = uid_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wjybxx.generatedmessage.PCSMessage.server_client_first_message) {
          return mergeFrom((com.wjybxx.generatedmessage.PCSMessage.server_client_first_message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wjybxx.generatedmessage.PCSMessage.server_client_first_message other) {
        if (other == com.wjybxx.generatedmessage.PCSMessage.server_client_first_message.getDefaultInstance()) return this;
        if (other.getUid() != 0) {
          setUid(other.getUid());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wjybxx.generatedmessage.PCSMessage.server_client_first_message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wjybxx.generatedmessage.PCSMessage.server_client_first_message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int uid_ ;
      /**
       * <code>int32 uid = 1;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>int32 uid = 1;</code>
       */
      public Builder setUid(int value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 uid = 1;</code>
       */
      public Builder clearUid() {
        
        uid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:wjybxx.server_client_first_message)
    }

    // @@protoc_insertion_point(class_scope:wjybxx.server_client_first_message)
    private static final com.wjybxx.generatedmessage.PCSMessage.server_client_first_message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wjybxx.generatedmessage.PCSMessage.server_client_first_message();
    }

    public static com.wjybxx.generatedmessage.PCSMessage.server_client_first_message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<server_client_first_message>
        PARSER = new com.google.protobuf.AbstractParser<server_client_first_message>() {
      public server_client_first_message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new server_client_first_message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<server_client_first_message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<server_client_first_message> getParserForType() {
      return PARSER;
    }

    public com.wjybxx.generatedmessage.PCSMessage.server_client_first_message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface client_server_pingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wjybxx.client_server_ping)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   *客户端发给服务器的ping包
   * </pre>
   *
   * Protobuf type {@code wjybxx.client_server_ping}
   */
  public  static final class client_server_ping extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wjybxx.client_server_ping)
      client_server_pingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use client_server_ping.newBuilder() to construct.
    private client_server_ping(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private client_server_ping() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private client_server_ping(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_client_server_ping_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_client_server_ping_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wjybxx.generatedmessage.PCSMessage.client_server_ping.class, com.wjybxx.generatedmessage.PCSMessage.client_server_ping.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wjybxx.generatedmessage.PCSMessage.client_server_ping)) {
        return super.equals(obj);
      }
      com.wjybxx.generatedmessage.PCSMessage.client_server_ping other = (com.wjybxx.generatedmessage.PCSMessage.client_server_ping) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wjybxx.generatedmessage.PCSMessage.client_server_ping parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.client_server_ping parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.client_server_ping parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.client_server_ping parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.client_server_ping parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.client_server_ping parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.client_server_ping parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.client_server_ping parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.client_server_ping parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.client_server_ping parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.client_server_ping parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.client_server_ping parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wjybxx.generatedmessage.PCSMessage.client_server_ping prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *客户端发给服务器的ping包
     * </pre>
     *
     * Protobuf type {@code wjybxx.client_server_ping}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wjybxx.client_server_ping)
        com.wjybxx.generatedmessage.PCSMessage.client_server_pingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_client_server_ping_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_client_server_ping_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wjybxx.generatedmessage.PCSMessage.client_server_ping.class, com.wjybxx.generatedmessage.PCSMessage.client_server_ping.Builder.class);
      }

      // Construct using com.wjybxx.generatedmessage.PCSMessage.client_server_ping.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_client_server_ping_descriptor;
      }

      public com.wjybxx.generatedmessage.PCSMessage.client_server_ping getDefaultInstanceForType() {
        return com.wjybxx.generatedmessage.PCSMessage.client_server_ping.getDefaultInstance();
      }

      public com.wjybxx.generatedmessage.PCSMessage.client_server_ping build() {
        com.wjybxx.generatedmessage.PCSMessage.client_server_ping result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wjybxx.generatedmessage.PCSMessage.client_server_ping buildPartial() {
        com.wjybxx.generatedmessage.PCSMessage.client_server_ping result = new com.wjybxx.generatedmessage.PCSMessage.client_server_ping(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wjybxx.generatedmessage.PCSMessage.client_server_ping) {
          return mergeFrom((com.wjybxx.generatedmessage.PCSMessage.client_server_ping)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wjybxx.generatedmessage.PCSMessage.client_server_ping other) {
        if (other == com.wjybxx.generatedmessage.PCSMessage.client_server_ping.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wjybxx.generatedmessage.PCSMessage.client_server_ping parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wjybxx.generatedmessage.PCSMessage.client_server_ping) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:wjybxx.client_server_ping)
    }

    // @@protoc_insertion_point(class_scope:wjybxx.client_server_ping)
    private static final com.wjybxx.generatedmessage.PCSMessage.client_server_ping DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wjybxx.generatedmessage.PCSMessage.client_server_ping();
    }

    public static com.wjybxx.generatedmessage.PCSMessage.client_server_ping getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<client_server_ping>
        PARSER = new com.google.protobuf.AbstractParser<client_server_ping>() {
      public client_server_ping parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new client_server_ping(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<client_server_ping> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<client_server_ping> getParserForType() {
      return PARSER;
    }

    public com.wjybxx.generatedmessage.PCSMessage.client_server_ping getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface server_client_pongOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wjybxx.server_client_pong)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 服务器返回给客户端pong包
   * </pre>
   *
   * Protobuf type {@code wjybxx.server_client_pong}
   */
  public  static final class server_client_pong extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wjybxx.server_client_pong)
      server_client_pongOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use server_client_pong.newBuilder() to construct.
    private server_client_pong(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private server_client_pong() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private server_client_pong(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_server_client_pong_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_server_client_pong_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wjybxx.generatedmessage.PCSMessage.server_client_pong.class, com.wjybxx.generatedmessage.PCSMessage.server_client_pong.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wjybxx.generatedmessage.PCSMessage.server_client_pong)) {
        return super.equals(obj);
      }
      com.wjybxx.generatedmessage.PCSMessage.server_client_pong other = (com.wjybxx.generatedmessage.PCSMessage.server_client_pong) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wjybxx.generatedmessage.PCSMessage.server_client_pong parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_pong parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_pong parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_pong parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_pong parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_pong parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_pong parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_pong parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_pong parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_pong parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_pong parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_pong parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wjybxx.generatedmessage.PCSMessage.server_client_pong prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 服务器返回给客户端pong包
     * </pre>
     *
     * Protobuf type {@code wjybxx.server_client_pong}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wjybxx.server_client_pong)
        com.wjybxx.generatedmessage.PCSMessage.server_client_pongOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_server_client_pong_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_server_client_pong_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wjybxx.generatedmessage.PCSMessage.server_client_pong.class, com.wjybxx.generatedmessage.PCSMessage.server_client_pong.Builder.class);
      }

      // Construct using com.wjybxx.generatedmessage.PCSMessage.server_client_pong.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_server_client_pong_descriptor;
      }

      public com.wjybxx.generatedmessage.PCSMessage.server_client_pong getDefaultInstanceForType() {
        return com.wjybxx.generatedmessage.PCSMessage.server_client_pong.getDefaultInstance();
      }

      public com.wjybxx.generatedmessage.PCSMessage.server_client_pong build() {
        com.wjybxx.generatedmessage.PCSMessage.server_client_pong result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wjybxx.generatedmessage.PCSMessage.server_client_pong buildPartial() {
        com.wjybxx.generatedmessage.PCSMessage.server_client_pong result = new com.wjybxx.generatedmessage.PCSMessage.server_client_pong(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wjybxx.generatedmessage.PCSMessage.server_client_pong) {
          return mergeFrom((com.wjybxx.generatedmessage.PCSMessage.server_client_pong)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wjybxx.generatedmessage.PCSMessage.server_client_pong other) {
        if (other == com.wjybxx.generatedmessage.PCSMessage.server_client_pong.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wjybxx.generatedmessage.PCSMessage.server_client_pong parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wjybxx.generatedmessage.PCSMessage.server_client_pong) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:wjybxx.server_client_pong)
    }

    // @@protoc_insertion_point(class_scope:wjybxx.server_client_pong)
    private static final com.wjybxx.generatedmessage.PCSMessage.server_client_pong DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wjybxx.generatedmessage.PCSMessage.server_client_pong();
    }

    public static com.wjybxx.generatedmessage.PCSMessage.server_client_pong getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<server_client_pong>
        PARSER = new com.google.protobuf.AbstractParser<server_client_pong>() {
      public server_client_pong parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new server_client_pong(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<server_client_pong> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<server_client_pong> getParserForType() {
      return PARSER;
    }

    public com.wjybxx.generatedmessage.PCSMessage.server_client_pong getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface server_client_one_requestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wjybxx.server_client_one_request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 param = 1;</code>
     */
    int getParam();
  }
  /**
   * <pre>
   *客户端发给服务器的请求
   * </pre>
   *
   * Protobuf type {@code wjybxx.server_client_one_request}
   */
  public  static final class server_client_one_request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wjybxx.server_client_one_request)
      server_client_one_requestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use server_client_one_request.newBuilder() to construct.
    private server_client_one_request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private server_client_one_request() {
      param_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private server_client_one_request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              param_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_server_client_one_request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_server_client_one_request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wjybxx.generatedmessage.PCSMessage.server_client_one_request.class, com.wjybxx.generatedmessage.PCSMessage.server_client_one_request.Builder.class);
    }

    public static final int PARAM_FIELD_NUMBER = 1;
    private int param_;
    /**
     * <code>int32 param = 1;</code>
     */
    public int getParam() {
      return param_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (param_ != 0) {
        output.writeInt32(1, param_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (param_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, param_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wjybxx.generatedmessage.PCSMessage.server_client_one_request)) {
        return super.equals(obj);
      }
      com.wjybxx.generatedmessage.PCSMessage.server_client_one_request other = (com.wjybxx.generatedmessage.PCSMessage.server_client_one_request) obj;

      boolean result = true;
      result = result && (getParam()
          == other.getParam());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PARAM_FIELD_NUMBER;
      hash = (53 * hash) + getParam();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wjybxx.generatedmessage.PCSMessage.server_client_one_request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *客户端发给服务器的请求
     * </pre>
     *
     * Protobuf type {@code wjybxx.server_client_one_request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wjybxx.server_client_one_request)
        com.wjybxx.generatedmessage.PCSMessage.server_client_one_requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_server_client_one_request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_server_client_one_request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wjybxx.generatedmessage.PCSMessage.server_client_one_request.class, com.wjybxx.generatedmessage.PCSMessage.server_client_one_request.Builder.class);
      }

      // Construct using com.wjybxx.generatedmessage.PCSMessage.server_client_one_request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        param_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_server_client_one_request_descriptor;
      }

      public com.wjybxx.generatedmessage.PCSMessage.server_client_one_request getDefaultInstanceForType() {
        return com.wjybxx.generatedmessage.PCSMessage.server_client_one_request.getDefaultInstance();
      }

      public com.wjybxx.generatedmessage.PCSMessage.server_client_one_request build() {
        com.wjybxx.generatedmessage.PCSMessage.server_client_one_request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wjybxx.generatedmessage.PCSMessage.server_client_one_request buildPartial() {
        com.wjybxx.generatedmessage.PCSMessage.server_client_one_request result = new com.wjybxx.generatedmessage.PCSMessage.server_client_one_request(this);
        result.param_ = param_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wjybxx.generatedmessage.PCSMessage.server_client_one_request) {
          return mergeFrom((com.wjybxx.generatedmessage.PCSMessage.server_client_one_request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wjybxx.generatedmessage.PCSMessage.server_client_one_request other) {
        if (other == com.wjybxx.generatedmessage.PCSMessage.server_client_one_request.getDefaultInstance()) return this;
        if (other.getParam() != 0) {
          setParam(other.getParam());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wjybxx.generatedmessage.PCSMessage.server_client_one_request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wjybxx.generatedmessage.PCSMessage.server_client_one_request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int param_ ;
      /**
       * <code>int32 param = 1;</code>
       */
      public int getParam() {
        return param_;
      }
      /**
       * <code>int32 param = 1;</code>
       */
      public Builder setParam(int value) {
        
        param_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 param = 1;</code>
       */
      public Builder clearParam() {
        
        param_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:wjybxx.server_client_one_request)
    }

    // @@protoc_insertion_point(class_scope:wjybxx.server_client_one_request)
    private static final com.wjybxx.generatedmessage.PCSMessage.server_client_one_request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wjybxx.generatedmessage.PCSMessage.server_client_one_request();
    }

    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<server_client_one_request>
        PARSER = new com.google.protobuf.AbstractParser<server_client_one_request>() {
      public server_client_one_request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new server_client_one_request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<server_client_one_request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<server_client_one_request> getParserForType() {
      return PARSER;
    }

    public com.wjybxx.generatedmessage.PCSMessage.server_client_one_request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface server_client_one_request_resultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wjybxx.server_client_one_request_result)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 param = 1;</code>
     */
    int getParam();

    /**
     * <code>string result = 2;</code>
     */
    java.lang.String getResult();
    /**
     * <code>string result = 2;</code>
     */
    com.google.protobuf.ByteString
        getResultBytes();
  }
  /**
   * <pre>
   *服务器的请求处理结果
   * </pre>
   *
   * Protobuf type {@code wjybxx.server_client_one_request_result}
   */
  public  static final class server_client_one_request_result extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wjybxx.server_client_one_request_result)
      server_client_one_request_resultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use server_client_one_request_result.newBuilder() to construct.
    private server_client_one_request_result(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private server_client_one_request_result() {
      param_ = 0;
      result_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private server_client_one_request_result(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              param_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              result_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_server_client_one_request_result_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_server_client_one_request_result_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result.class, com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result.Builder.class);
    }

    public static final int PARAM_FIELD_NUMBER = 1;
    private int param_;
    /**
     * <code>int32 param = 1;</code>
     */
    public int getParam() {
      return param_;
    }

    public static final int RESULT_FIELD_NUMBER = 2;
    private volatile java.lang.Object result_;
    /**
     * <code>string result = 2;</code>
     */
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        result_ = s;
        return s;
      }
    }
    /**
     * <code>string result = 2;</code>
     */
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (param_ != 0) {
        output.writeInt32(1, param_);
      }
      if (!getResultBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, result_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (param_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, param_);
      }
      if (!getResultBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, result_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result)) {
        return super.equals(obj);
      }
      com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result other = (com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result) obj;

      boolean result = true;
      result = result && (getParam()
          == other.getParam());
      result = result && getResult()
          .equals(other.getResult());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PARAM_FIELD_NUMBER;
      hash = (53 * hash) + getParam();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *服务器的请求处理结果
     * </pre>
     *
     * Protobuf type {@code wjybxx.server_client_one_request_result}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wjybxx.server_client_one_request_result)
        com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_resultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_server_client_one_request_result_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_server_client_one_request_result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result.class, com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result.Builder.class);
      }

      // Construct using com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        param_ = 0;

        result_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wjybxx.generatedmessage.PCSMessage.internal_static_wjybxx_server_client_one_request_result_descriptor;
      }

      public com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result getDefaultInstanceForType() {
        return com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result.getDefaultInstance();
      }

      public com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result build() {
        com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result buildPartial() {
        com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result result = new com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result(this);
        result.param_ = param_;
        result.result_ = result_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result) {
          return mergeFrom((com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result other) {
        if (other == com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result.getDefaultInstance()) return this;
        if (other.getParam() != 0) {
          setParam(other.getParam());
        }
        if (!other.getResult().isEmpty()) {
          result_ = other.result_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int param_ ;
      /**
       * <code>int32 param = 1;</code>
       */
      public int getParam() {
        return param_;
      }
      /**
       * <code>int32 param = 1;</code>
       */
      public Builder setParam(int value) {
        
        param_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 param = 1;</code>
       */
      public Builder clearParam() {
        
        param_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object result_ = "";
      /**
       * <code>string result = 2;</code>
       */
      public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          result_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string result = 2;</code>
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string result = 2;</code>
       */
      public Builder setResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string result = 2;</code>
       */
      public Builder clearResult() {
        
        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }
      /**
       * <code>string result = 2;</code>
       */
      public Builder setResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        result_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:wjybxx.server_client_one_request_result)
    }

    // @@protoc_insertion_point(class_scope:wjybxx.server_client_one_request_result)
    private static final com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result();
    }

    public static com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<server_client_one_request_result>
        PARSER = new com.google.protobuf.AbstractParser<server_client_one_request_result>() {
      public server_client_one_request_result parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new server_client_one_request_result(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<server_client_one_request_result> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<server_client_one_request_result> getParserForType() {
      return PARSER;
    }

    public com.wjybxx.generatedmessage.PCSMessage.server_client_one_request_result getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wjybxx_server_client_first_message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wjybxx_server_client_first_message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wjybxx_client_server_ping_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wjybxx_client_server_ping_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wjybxx_server_client_pong_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wjybxx_server_client_pong_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wjybxx_server_client_one_request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wjybxx_server_client_one_request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wjybxx_server_client_one_request_result_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wjybxx_server_client_one_request_result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023client_server.proto\022\006wjybxx\"8\n\033server_" +
      "client_first_message\022\013\n\003uid\030\001 \001(\005\022\014\n\004nam" +
      "e\030\002 \001(\t\"\024\n\022client_server_ping\"\024\n\022server_" +
      "client_pong\"*\n\031server_client_one_request" +
      "\022\r\n\005param\030\001 \001(\005\"A\n server_client_one_req" +
      "uest_result\022\r\n\005param\030\001 \001(\005\022\016\n\006result\030\002 \001" +
      "(\tB+\n\033com.wjybxx.generatedmessageB\nPCSMe" +
      "ssageH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_wjybxx_server_client_first_message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wjybxx_server_client_first_message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wjybxx_server_client_first_message_descriptor,
        new java.lang.String[] { "Uid", "Name", });
    internal_static_wjybxx_client_server_ping_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wjybxx_client_server_ping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wjybxx_client_server_ping_descriptor,
        new java.lang.String[] { });
    internal_static_wjybxx_server_client_pong_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_wjybxx_server_client_pong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wjybxx_server_client_pong_descriptor,
        new java.lang.String[] { });
    internal_static_wjybxx_server_client_one_request_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_wjybxx_server_client_one_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wjybxx_server_client_one_request_descriptor,
        new java.lang.String[] { "Param", });
    internal_static_wjybxx_server_client_one_request_result_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_wjybxx_server_client_one_request_result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wjybxx_server_client_one_request_result_descriptor,
        new java.lang.String[] { "Param", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
